export const categories = [
  { name: "Organic Foods", href: "/category/organic-foods" },
  { name: "Electronics", href: "/category/electronics" },
  { name: "Clothing", href: "/category/clothing" },
  { name: "Shoes", href: "/category/shoes" },
  { name: "Accessories", href: "/category/accessories" },
  { name: "Lifestyle", href: "/category/lifestyle" },
  { name: "Beauty & Personal Care", href: "/category/beauty-personal-care" },
  { name: "Toys & Baby Products", href: "/category/toys-baby-products" },
  { name: "Mobile & Computer", href: "/category/mobile-computer" },
];

export const carouselSlides = [
  {
    id: 1,
    title: "Pure Honey. Powerful Nuts.",
    subtitle:
      "A wholesome blend crafted for natural energy and everyday wellness.",
    buttonText: "Shop Now",
    bgColor: "bg-[#d4e4c4]",
    textColor: "text-[#1e3a5f]",
    buttonColor: "bg-[#2d8a5e] hover:bg-[#236e4a]",
    image: "/assets/hero/hero-carousel-1.png",
  },
  {
    id: 2,
    title: "Fresh Organic Fruits.",
    subtitle: "Handpicked from local farms, delivered fresh to your doorstep.",
    buttonText: "Order Now",
    bgColor: "bg-[#fce4d6]",
    textColor: "text-[#8b4513]",
    buttonColor: "bg-[#e07020] hover:bg-[#c45e18]",
    image: "/assets/hero/hero-carousel-1.png",
  },
  {
    id: 3,
    title: "Premium Dry Fruits.",
    subtitle: "Rich in nutrients, perfect for your daily health routine.",
    buttonText: "Explore",
    bgColor: "bg-[#f5e6d3]",
    textColor: "text-[#5c4033]",
    buttonColor: "bg-[#8b5a2b] hover:bg-[#6d4522]",
    image: "/assets/hero/hero-carousel-1.png",
  },
  {
    id: 4,
    title: "Natural Herbal Teas.",
    subtitle: "Soothe your senses with our aromatic herbal collection.",
    buttonText: "Discover",
    bgColor: "bg-[#e8f5e9]",
    textColor: "text-[#2e7d32]",
    buttonColor: "bg-[#388e3c] hover:bg-[#2e7d32]",
    image: "/assets/hero/hero-carousel-1.png",
  },
  {
    id: 5,
    title: "Artisan Nut Butters.",
    subtitle: "Creamy, smooth, and made with 100% natural ingredients.",
    buttonText: "Buy Now",
    bgColor: "bg-[#fff3e0]",
    textColor: "text-[#bf360c]",
    buttonColor: "bg-[#e65100] hover:bg-[#bf360c]",
    image: "/assets/hero/hero-carousel-1.png",
  },
];

export const productCategories = [
  {
    name: "Honey",
    products: "125+ Products",
    image: "/assets/categories/category-1.png",
  },
  {
    name: "Ghee",
    products: "125+ Products",
    image: "/assets/categories/category-2.png",
  },
  {
    name: "Spices",
    products: "125+ Products",
    image: "/assets/categories/category-3.png",
  },
  {
    name: "Headphones",
    products: "125+ Products",
    image: "/assets/categories/category-1.png",
  },
  {
    name: "Blender",
    products: "125+ Products",
    image: "/assets/categories/category-2.png",
  },
  {
    name: "Watches",
    products: "125+ Products",
    image: "/assets/categories/category-3.png",
  },
  {
    name: "Toys",
    products: "125+ Products",
    image: "/assets/categories/category-1.png",
  },
  {
    name: "Stationery",
    products: "125+ Products",
    image: "/assets/categories/category-2.png",
  },
  {
    name: "Skin Care",
    products: "125+ Products",
    image: "/assets/categories/category-3.png",
  },
  {
    name: "Makeup",
    products: "125+ Products",
    image: "/assets/categories/category-1.png",
  },
  {
    name: "Makeup",
    products: "125+ Products",
    image: "/assets/categories/category-1.png",
  },
  {
    name: "Makeup",
    products: "125+ Products",
    image: "/assets/categories/category-1.png",
  },
  {
    name: "Makeup",
    products: "125+ Products",
    image: "/assets/categories/category-1.png",
  },
  {
    name: "Makeup",
    products: "125+ Products",
    image: "/assets/categories/category-1.png",
  },
  {
    name: "Makeup",
    products: "125+ Products",
    image: "/assets/categories/category-1.png",
  },
];

export const sales = [
  {
    id: 1,
    title: "Daily Snacks",
    image: "/assets/flash-sales/flash-sales-1.png",
    bgColor: "bg-lime-100",
    buttonColor: "bg-emerald-600 hover:bg-emerald-700",
    buttonTextColor: "text-white",
    endDate: new Date(
      Date.now() + 19 * 24 * 60 * 60 * 1000 + 10 * 60 * 60 * 1000
    ),
  },
  {
    id: 2,
    title: "Stationery Products",
    image: "/assets/flash-sales/flash-sales-2.png",
    bgColor: "bg-red-100",
    buttonColor: "bg-orange-500 hover:bg-orange-600",
    buttonTextColor: "text-white",
    endDate: new Date(
      Date.now() + 19 * 24 * 60 * 60 * 1000 + 10 * 60 * 60 * 1000
    ),
  },
  {
    id: 3,
    title: "Electronics",
    image: "/assets/flash-sales/flash-sales-1.png",
    bgColor: "bg-blue-100",
    buttonColor: "bg-blue-600 hover:bg-blue-700",
    buttonTextColor: "text-white",
    endDate: new Date(
      Date.now() + 15 * 24 * 60 * 60 * 1000 + 8 * 60 * 60 * 1000
    ),
  },
  {
    id: 4,
    title: "Home Decor",
    image: "/assets/flash-sales/flash-sales-2.png",
    bgColor: "bg-amber-100",
    buttonColor: "bg-amber-600 hover:bg-amber-700",
    buttonTextColor: "text-white",
    endDate: new Date(
      Date.now() + 12 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000
    ),
  },
  {
    id: 5,
    title: "Fashion Wear",
    image: "/assets/flash-sales/flash-sales-1.png",
    bgColor: "bg-purple-100",
    buttonColor: "bg-purple-600 hover:bg-purple-700",
    buttonTextColor: "text-white",
    endDate: new Date(
      Date.now() + 10 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000
    ),
  },
  {
    id: 6,
    title: "Kitchen Essentials",
    image: "/assets/flash-sales/flash-sales-2.png",
    bgColor: "bg-green-100",
    buttonColor: "bg-green-600 hover:bg-green-700",
    buttonTextColor: "text-white",
    endDate: new Date(
      Date.now() + 8 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000
    ),
  },
];

export const offers = [
  {
    id: 1,
    title: "Mega Electronics Sale",
    image: "/assets/flash-sales/flash-sales-1.png",
    bgColor: "bg-blue-100",
    buttonColor: "bg-blue-600 hover:bg-blue-700",
    buttonTextColor: "text-white",
    endDate: "12-30 December 2025",
  },
  {
    id: 2,
    title: "Fashion Festival",
    image: "/assets/flash-sales/flash-sales-2.png",
    bgColor: "bg-purple-100",
    buttonColor: "bg-purple-600 hover:bg-purple-700",
    buttonTextColor: "text-white",
    endDate: "12-30 December 2025",
  },
];

export const brands = [
  { name: "Ghorer Bazar", logo: "/assets/brands/brand-1.png" },
  { name: "Karkuma", logo: "/assets/brands/brand-2.png" },
  { name: "Naturo", logo: "/assets/brands/brand-3.png" },
  { name: "Acure Bd", logo: "/assets/brands/brand-1.png" },
  { name: "Khaas Food", logo: "/assets/brands/brand-2.png" },
  { name: "Panash Food", logo: "/assets/brands/brand-3.png" },
  { name: "Ecory", logo: "/assets/brands/brand-1.png" },
  { name: "Bonobhumi", logo: "/assets/brands/brand-2.png" },
  { name: "Bonobhumi", logo: "/assets/brands/brand-3.png" },
  { name: "Bonobhumi", logo: "/assets/brands/brand-1.png" },
  { name: "Bonobhumi", logo: "/assets/brands/brand-2.png" },
];

export const flashSaleProducts = [
  {
    id: 1,
    name: "C-500 Antioxidant Protect High Quality Dietary Supplement",
    brand: "Brand Name",
    image: "/assets/product/product-1.png",
    currentPrice: 14.99,
    oldPrice: 16.99,
    rating: 4.8,
    sold: 18,
    total: 40,
  },
  {
    id: 2,
    name: "Vitamin D3 Immune Support and Energy Booster",
    brand: "Health Plus",
    image: "/assets/product/product-2.png",
    currentPrice: 22.5,
    oldPrice: 29.99,
    rating: 4.6,
    sold: 25,
    total: 50,
  },
  {
    id: 3,
    name: "Omega-3 Fish Oil Supplement for Healthy Brain and Eyes",
    brand: "Nature's Best",
    image: "/assets/product/product-3.png",
    currentPrice: 18.75,
    oldPrice: 24.99,
    rating: 4.9,
    sold: 32,
    total: 60,
  },
  {
    id: 4,
    name: "Probiotic Digestive Health Support for Gut Health",
    brand: "Gut Health Co",
    image: "/assets/product/product-4.png",
    currentPrice: 31.99,
    oldPrice: 39.99,
    rating: 4.7,
    sold: 15,
    total: 35,
  },
  {
    id: 5,
    name: "Multivitamin Daily Complete for Boosting Energy and Well-being",
    brand: "VitaLife",
    image: "/assets/product/product-5.png",
    currentPrice: 19.99,
    oldPrice: 27.99,
    rating: 4.5,
    sold: 28,
    total: 45,
  },
  {
    id: 6,
    name: "Multivitamin Daily Complete for Boosting Energy and Well-being",
    brand: "VitaLife",
    image: "/assets/product/product-5.png",
    currentPrice: 19.99,
    oldPrice: 27.99,
    rating: 4.5,
    sold: 28,
    total: 45,
  },
];

export const products = [
  {
    id: 1,
    name: "C-500 Antioxidant Protect Dietary Supplement",
    category: "Vitamins & Supplements",
    image: "/assets/product/product-1.png",
    price: 14.99,
    rating: 4.8,
  },
  {
    id: 2,
    name: "Vitamin D3 Immune Support and Energy Booster",
    category: "Vitamins & Supplements",
    image: "/assets/product/product-2.png",
    price: 22.5,
    rating: 4.6,
  },
  {
    id: 3,
    name: "Omega-3 Fish Oil Supplement for Healthy Brain and Eyes",
    category: "Omega & Fish Oil",
    image: "/assets/product/product-3.png",
    price: 18.75,
    rating: 4.9,
  },
  {
    id: 4,
    name: "Probiotic Digestive Health Support for Gut Health",
    category: "Probiotics",
    image: "/assets/product/product-4.png",
    price: 31.99,
    rating: 4.7,
  },
  {
    id: 5,
    name: "Multivitamin Daily Complete for Boosting Energy and Well-being",
    category: "Multivitamins",
    image: "/assets/product/product-5.png",
    price: 19.99,
    rating: 4.5,
  },
  {
    id: 6,
    name: "Organic Turmeric Curcumin with Bioperine",
    category: "Herbal Supplements",
    image: "/assets/product/product-1.png",
    price: 24.99,
    rating: 4.8,
  },
  {
    id: 7,
    name: "Magnesium Glycinate for Sleep and Relaxation",
    category: "Minerals",
    image: "/assets/product/product-2.png",
    price: 16.75,
    rating: 4.6,
  },
  {
    id: 8,
    name: "Collagen Peptides Powder for Skin and Joint Health",
    category: "Beauty & Wellness",
    image: "/assets/product/product-3.png",
    price: 28.99,
    rating: 4.9,
  },
  {
    id: 9,
    name: "B-Complex Vitamin for Energy and Stress Relief",
    category: "B Vitamins",
    image: "/assets/product/product-4.png",
    price: 21.5,
    rating: 4.4,
  },
  {
    id: 10,
    name: "Zinc Picolinate Immune Support Supplement",
    category: "Minerals",
    image: "/assets/product/product-5.png",
    price: 13.99,
    rating: 4.7,
  },
  {
    id: 11,
    name: "Iron Ferrous Sulfate for Anemia Support",
    category: "Minerals",
    image: "/assets/product/product-1.png",
    price: 15.25,
    rating: 4.5,
  },
  {
    id: 12,
    name: "Vitamin C with Rose Hips Antioxidant",
    category: "Vitamins & Supplements",
    image: "/assets/product/product-2.png",
    price: 12.99,
    rating: 4.8,
  },
  {
    id: 13,
    name: "Wireless Bluetooth Headphones Pro",
    category: "Electronics",
    image: "/assets/product/product-3.png",
    price: 89.99,
    rating: 4.7,
  },
  {
    id: 14,
    name: "Smart Watch Series 5",
    category: "Electronics",
    image: "/assets/product/product-4.png",
    price: 299.99,
    rating: 4.8,
  },
  {
    id: 15,
    name: "4K Webcam with Microphone",
    category: "Electronics",
    image: "/assets/product/product-5.png",
    price: 79.99,
    rating: 4.5,
  },
  {
    id: 16,
    name: "Wireless Gaming Mouse RGB",
    category: "Electronics",
    image: "/assets/product/product-1.png",
    price: 49.99,
    rating: 4.6,
  },
  {
    id: 17,
    name: "Mechanical Keyboard Gaming",
    category: "Electronics",
    image: "/assets/product/product-2.png",
    price: 129.99,
    rating: 4.9,
  },
  {
    id: 18,
    name: "Men's Cotton T-Shirt Premium",
    category: "Clothing",
    image: "/assets/product/product-3.png",
    price: 24.99,
    rating: 4.4,
  },
  {
    id: 19,
    name: "Women's Summer Dress Floral",
    category: "Clothing",
    image: "/assets/product/product-4.png",
    price: 39.99,
    rating: 4.6,
  },
  {
    id: 20,
    name: "Men's Slim Fit Jeans",
    category: "Clothing",
    image: "/assets/product/product-5.png",
    price: 59.99,
    rating: 4.5,
  },
  {
    id: 21,
    name: "Women's Yoga Pants Athletic",
    category: "Clothing",
    image: "/assets/product/product-1.png",
    price: 34.99,
    rating: 4.7,
  },
  {
    id: 22,
    name: "Men's Polo Shirt Classic",
    category: "Clothing",
    image: "/assets/product/product-2.png",
    price: 29.99,
    rating: 4.3,
  },
  {
    id: 23,
    name: "Running Shoes Men's Athletic",
    category: "Shoes",
    image: "/assets/product/product-3.png",
    price: 79.99,
    rating: 4.8,
  },
  {
    id: 24,
    name: "Women's Walking Shoes Comfort",
    category: "Shoes",
    image: "/assets/product/product-4.png",
    price: 69.99,
    rating: 4.6,
  },
  {
    id: 25,
    name: "Men's Leather Boots Formal",
    category: "Shoes",
    image: "/assets/product/product-5.png",
    price: 129.99,
    rating: 4.7,
  },
  {
    id: 26,
    name: "Women's High Heels Elegant",
    category: "Shoes",
    image: "/assets/product/product-1.png",
    price: 89.99,
    rating: 4.5,
  },
  {
    id: 27,
    name: "Kids Sneakers Colorful",
    category: "Shoes",
    image: "/assets/product/product-2.png",
    price: 39.99,
    rating: 4.8,
  },
  {
    id: 28,
    name: "Leather Wallet Men's Genuine",
    category: "Accessories",
    image: "/assets/product/product-3.png",
    price: 49.99,
    rating: 4.6,
  },
  {
    id: 29,
    name: "Women's Handbag Designer",
    category: "Accessories",
    image: "/assets/product/product-4.png",
    price: 149.99,
    rating: 4.7,
  },
  {
    id: 30,
    name: "Sunglasses Polarized UV Protection",
    category: "Accessories",
    image: "/assets/product/product-5.png",
    price: 59.99,
    rating: 4.5,
  },
  {
    id: 31,
    name: "Watch Analog Classic",
    category: "Accessories",
    image: "/assets/product/product-1.png",
    price: 99.99,
    rating: 4.8,
  },
  {
    id: 32,
    name: "Belt Leather Men's Dress",
    category: "Accessories",
    image: "/assets/product/product-2.png",
    price: 39.99,
    rating: 4.4,
  },
  {
    id: 33,
    name: "Educational Building Blocks Set",
    category: "Toys & Baby Products",
    image: "/assets/product/product-3.png",
    price: 29.99,
    rating: 4.9,
  },
  {
    id: 34,
    name: "Baby Diapers Premium Pack",
    category: "Toys & Baby Products",
    image: "/assets/product/product-4.png",
    price: 24.99,
    rating: 4.6,
  },
  {
    id: 35,
    name: "Teddy Bear Soft Plush",
    category: "Toys & Baby Products",
    image: "/assets/product/product-5.png",
    price: 19.99,
    rating: 4.8,
  },
  {
    id: 36,
    name: "Baby Formula Organic",
    category: "Toys & Baby Products",
    image: "/assets/product/product-1.png",
    price: 34.99,
    rating: 4.7,
  },
  {
    id: 37,
    name: "Remote Control Car Toy",
    category: "Toys & Baby Products",
    image: "/assets/product/product-2.png",
    price: 44.99,
    rating: 4.5,
  },
  {
    id: 38,
    name: "Smartphone Latest Model",
    category: "Mobile & Computer",
    image: "/assets/product/product-3.png",
    price: 699.99,
    rating: 4.8,
  },
  {
    id: 39,
    name: "Laptop Gaming High Performance",
    category: "Mobile & Computer",
    image: "/assets/product/product-4.png",
    price: 1299.99,
    rating: 4.7,
  },
  {
    id: 40,
    name: "Tablet 10 inch WiFi",
    category: "Mobile & Computer",
    image: "/assets/product/product-5.png",
    price: 329.99,
    rating: 4.6,
  },
  {
    id: 41,
    name: "Wireless Charger Fast",
    category: "Mobile & Computer",
    image: "/assets/product/product-1.png",
    price: 29.99,
    rating: 4.4,
  },
  {
    id: 42,
    name: "USB-C Hub Multi-Port",
    category: "Mobile & Computer",
    image: "/assets/product/product-2.png",
    price: 39.99,
    rating: 4.5,
  },
  {
    id: 43,
    name: "Bluetooth Speaker Portable",
    category: "Electronics",
    image: "/assets/product/product-3.png",
    price: 59.99,
    rating: 4.7,
  },
  {
    id: 44,
    name: "Women's Scarf Silk",
    category: "Accessories",
    image: "/assets/product/product-4.png",
    price: 29.99,
    rating: 4.6,
  },
  {
    id: 45,
    name: "Baby Stroller Travel System",
    category: "Toys & Baby Products",
    image: "/assets/product/product-5.png",
    price: 199.99,
    rating: 4.8,
  },
];

export const topBrands = [
  {
    id: 1,
    name: "Khaas Food",
    products: 690,
    productImages: [
      "/assets/product/product-1.png",
      "/assets/product/product-2.png",
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
    ],
    bgColor: "#F4F6E6",
  },
  {
    id: 2,
    name: "Ghorer Bazar",
    products: 450,
    productImages: [
      "/assets/product/product-2.png",
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
      "/assets/product/product-1.png",
    ],
    bgColor: "#E6F6F6",
  },
  {
    id: 3,
    name: "Karkuma",
    products: 320,
    productImages: [
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
      "/assets/product/product-1.png",
      "/assets/product/product-2.png",
    ],
    bgColor: "#F6E6F6",
  },
  {
    id: 4,
    name: "Naturo",
    products: 280,
    productImages: [
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
      "/assets/product/product-1.png",
      "/assets/product/product-2.png",
      "/assets/product/product-3.png",
    ],
    bgColor: "#DEE6F3",
  },
  {
    id: 5,
    name: "Acure Bd",
    products: 195,
    productImages: [
      "/assets/product/product-5.png",
      "/assets/product/product-1.png",
      "/assets/product/product-2.png",
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
    ],
    bgColor: "#DAF2DB",
  },
  {
    id: 6,
    name: "Panash Food",
    products: 150,
    productImages: [
      "/assets/product/product-1.png",
      "/assets/product/product-2.png",
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
    ],
    bgColor: "#FEFCE8",
  },
  {
    id: 7,
    name: "Ecory",
    products: 125,
    productImages: [
      "/assets/product/product-2.png",
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
      "/assets/product/product-1.png",
    ],
    bgColor: "#FEF2F2",
  },
  {
    id: 8,
    name: "Bonobhumi",
    products: 98,
    productImages: [
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
      "/assets/product/product-1.png",
      "/assets/product/product-2.png",
    ],
    bgColor: "#EEF2FF",
  },
  {
    id: 8,
    name: "Bonobhumi",
    products: 98,
    productImages: [
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
      "/assets/product/product-1.png",
      "/assets/product/product-2.png",
    ],
    bgColor: "#EEF2FF",
  },
  {
    id: 8,
    name: "Bonobhumi",
    products: 98,
    productImages: [
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
      "/assets/product/product-1.png",
      "/assets/product/product-2.png",
    ],
    bgColor: "#EEF2FF",
  },
  {
    id: 8,
    name: "Bonobhumi",
    products: 98,
    productImages: [
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
      "/assets/product/product-1.png",
      "/assets/product/product-2.png",
    ],
    bgColor: "#EEF2FF",
  },
  {
    id: 8,
    name: "Bonobhumi",
    products: 98,
    productImages: [
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
      "/assets/product/product-1.png",
      "/assets/product/product-2.png",
    ],
    bgColor: "#EEF2FF",
  },
  {
    id: 8,
    name: "Bonobhumi",
    products: 98,
    productImages: [
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
      "/assets/product/product-1.png",
      "/assets/product/product-2.png",
    ],
    bgColor: "#F4F6E6",
  },
  {
    id: 8,
    name: "Bonobhumi",
    products: 98,
    productImages: [
      "/assets/product/product-3.png",
      "/assets/product/product-4.png",
      "/assets/product/product-5.png",
      "/assets/product/product-1.png",
      "/assets/product/product-2.png",
    ],
    bgColor: "#EEF2FF",
  },
];

export const SIDEBAR_CATEGORIES = [
  { name: "Dates", count: 87, slug: "dates" },
  { name: "Honey", count: 118, slug: "honey" },
  { name: "Oils & Ghee", count: 93, slug: "oils-ghee" },
  { name: "Organic Rice & Grains", count: 22, slug: "rice-grains" },
  { name: "Dry Fruits", count: 105, slug: "dry-fruits" },
  { name: "Spices & Herbs", count: 238, slug: "spices-herbs" },
  { name: "Snacks & Superfoods", count: 40, slug: "snacks-superfoods" },
  { name: "Natural Sweeteners", count: 12, slug: "sweeteners" },
  { name: "Natural Sweeteners", count: 12, slug: "sweeteners" },
  { name: "Natural Sweeteners", count: 12, slug: "sweeteners" },
  { name: "Natural Sweeteners", count: 12, slug: "sweeteners" },
  { name: "Natural Sweeteners", count: 12, slug: "sweeteners" },
];
